ProyectoTEA/AppTEA/urls.py
# -*- coding: utf-8 -*-

"""Configuración de urls de AppTEA

Variables:
:urlpatterns: lista las rutas de los URLs que redireccionan a las vistas.

Rutas (URLs):
:loguearse: 
:desloguearse:
:pacientes:
:profesionales:
:areas:
:facturacion:
:cobranza:
"""

from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView

V = 'AppTEA.views.'

urlpatterns = [
    # Redireccion a la pagina de pacientes
    url(r'^$', RedirectView.as_view(url='pacientes/', permanent=True)),

    url(r'^loguearse/$', V + 'usuario.loguearse', name='loguearse'),
    url(r'^desloguearse/$', V + 'usuario.desloguearse', name='desloguearse'),

    url(r'^pacientes/$', V + 'paciente.pacientes', name='pacientes'),
    url(r'^pacientes/registrar/$', V + 'paciente.registrar', name='registrarPaciente'),
    url(r'^pacientes/(?P<id_paciente>\d+)/$', V + 'paciente.ver', name='verPaciente'),
    url(r'^pacientes/(?P<id_paciente>\d+)/editar/$', V + 'paciente.editar', name='editarPaciente'),
    url(r'^pacientes/(?P<id_paciente>\d+)/desactivar/$', V + 'paciente.desactivar', name='desactivarPaciente'),
    
    url(r'^pacientes/(?P<id_paciente>\d+)/historia/$', V + 'paciente.historia.informes', name='historia'),
    url(r'^pacientes/(?P<id_paciente>\d+)/historia/registrar/$', V + 'paciente.historia.registrar', name='registrarInforme'),
    url(r'^pacientes/(?P<id_paciente>\d+)/historia/(?P<id_informe>\d+)/$', V + 'paciente.historia.ver', name='verInforme'),
    url(r'^pacientes/(?P<id_paciente>\d+)/historia/(?P<id_informe>\d+)/editar/$', V + 'paciente.historia.editar', name='editarInforme'),
    url(r'^pacientes/(?P<id_paciente>\d+)/historia/(?P<id_informe>\d+)/desactivar/$', V + 'paciente.historia.desactivar', name='desactivarInforme'),

    url(r'^pacientes/(?P<id_paciente>\d+)/presupuestos/$', V + 'paciente.presupuesto.presupuestos', name='presupuestos'),
    url(r'^pacientes/(?P<id_paciente>\d+)/presupuestos/registrar/$', V + 'paciente.presupuesto.registrar', name='registrarPresupuesto'),
    url(r'^pacientes/(?P<id_paciente>\d+)/presupuestos/(?P<id_presupuesto>\d+)/pdf$', V + 'paciente.presupuesto.presupuesto_pdf', name='pdfPresupuesto'),
    #url(r'^pacientes/(?P<id_paciente>\d+)/presupuestos/(?P<id_presupuesto>\d+)/editar/$', V + 'paciente.presupuesto.editar', name='editarPresupuesto'),
    #url(r'^pacientes/(?P<id_paciente>\d+)/presupuestos/(?P<id_presupuesto>\d+)/desactivar/$', V + 'paciente.presupuesto.desactivar', name='desactivarPresupuesto'),


    url(r'^profesionales/$', V + 'profesional.profesionales', name='profesionales'),
    url(r'^profesionales/registrar/$', V + 'profesional.registrar', name='registrarProfesional'),
    url(r'^profesionales/(?P<id_profesional>\d+)/$', V + 'profesional.ver', name='verProfesional'),
    url(r'^profesionales/(?P<id_profesional>\d+)/editar/$', V + 'profesional.editar', name='editarProfesional'),
    url(r'^profesionales/(?P<id_profesional>\d+)/desactivar/$', V + 'profesional.desactivar', name='desactivarProfesional'),

    url(r'^areas/$', V + 'area.areas', name='areas'),
    url(r'^areas/registrar/$', V + 'area.registrar', name='registrarArea'),
    url(r'^areas/(?P<id_area>\d+)/$', V + 'area.ver', name='verArea'),
    url(r'^areas/(?P<id_area>\d+)/editar/$', V + 'area.editar', name='editarArea'),
    url(r'^areas/(?P<id_area>\d+)/desactivar/$', V + 'area.desactivar', name='desactivarArea'),

    url(r'^facturacion/$', V + 'facturacion.mostrar', name='facturacion'),
    url(r'^cobranza/$', V + 'cobranza.mostrar', name='cobranza'),
    url(r'^cobranza/total$', V + 'cobranza.mostrar_todas', name='cobranza_total')
]

ProyectoTEA/ProyectoTEA/urls.py
from django.conf.urls import include, url, patterns
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    url(r'^', include('AppTEA.urls', namespace="apptea")),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

# Errores
handler403 = 'AppTEA.views.error.denegado'
handler404 = 'AppTEA.views.error.error404'
handler500 = 'AppTEA.views.error.error500'

ProyectoTEA/AppTEA/views/area.py
# -*- coding: utf-8 -*-

from AppTEA.views import *


"""
Vista del Administrador para gestionar las áreas existentes.
"""
@permission_required('AppTEA.areas', raise_exception=True)
def areas(request):
    # Si es Administrador
    if request.user.is_staff:

        if request.method == "POST" and request.is_ajax():
            filtro = request.POST['filtro']
            areas = Area.objects.filter(Q(nombre__icontains=filtro),
                                                is_active=True).order_by("nombre")
            ids = []

            for a in areas:
                ids.append(a.id)

            return JsonResponse({"ids": ids})

        else:
            context = {"areas": Area.objects.filter(is_active=True).order_by("nombre"),
                       "btn_enlace": "registrar/",
                       "btn_icono": "add",
                       "placeholder": "Nombre del area",
                       "url_filtro": reverse('apptea:areas')}
            
            return render(request, "administrador/areas/index.html", context)
    else:
        return HttpResponse("Acceso denegado")


"""
Vista del Administrador para registrar una nueva area
"""
@permission_required('AppTEA.areas', raise_exception=True)
def registrar(request):
    context = {"btn_enlace": "..",
               "btn_icono": "arrow_back"}
    if request.method == 'POST':
        fieldnombre = request.POST['nombre']
        if fieldnombre == "":
            context['err'] = "el nombre esta vacio"
            return render(request, "administrador/areas/editar.html", context)
        nuevaArea = Area(nombre = fieldnombre)
        nuevaArea.save()
        return redirect("..")
    else:
        return render(request, "administrador/areas/registrar.html", context)


"""
Vista del Administrador para ver un area específica
"""
@permission_required('AppTEA.areas', raise_exception=True)
def ver(request, id_area):
    area = Area.objects.get(pk=id_area)
    context = {"area": Area.objects.get(pk=id_area),
               "btn_enlace": "..",
               "btn_icono": "arrow_back"}

    return render(request, "administrador/areas/ver.html", context)


"""
Vista del Administrador para editar un area
"""
@permission_required('AppTEA.areas', raise_exception=True)
def editar(request, id_area):
    area = Area.objects.get(pk=id_area)
    context = {"area": Area.objects.get(pk=id_area),
               "btn_enlace": "../..",
               "btn_icono": "arrow_back"}
               
    if request.method == 'POST':
        if request.POST['nombre'] == "":
            context['err'] = "el nombre esta vacio"
            return render(request, "administrador/areas/editar.html", context)
        area.nombre = request.POST['nombre']
        area.save()
        return redirect("../..")
    else:
        return render(request, "administrador/areas/editar.html", context)

"""
Vista del Administrador para desactivar area.
"""
@permission_required('AppTEA.areas', raise_exception=True)
def desactivar(request, id_area):
    area = Area.objects.get(pk=id_area)
    area.is_active = False
    area.save()
    return redirect("apptea:areas")

ProyectoTEA/AppTEA/views/cobranza.py
# -*- coding: utf-8 -*-

from AppTEA.views import *


"""
Vista de cobranza.

* En caso de ser Administrador:
    Información de todos los profesionales con sus respectivos aportes.

* En caso de ser Profesional:
    Información de aportes propios.
"""
@login_required
def mostrar(request):
    meses_aporte = []
    mes_year = datetime.now().strftime('%Y-%m')
    if request.user.is_staff == True:
        objects = Mes_presupuesto.objects.filter()
    else:
        objects = Mes_presupuesto.objects.filter(profesional = request.user.pk)
    for mes_aporte in objects:
        if mes_aporte.mes.strftime('%Y-%m') == mes_year:
            meses_aporte.append(mes_aporte)
            
    context = {
               "meses_aporte":meses_aporte
               }
                      
    return render(request, "comun/cobranza/index.html", context)

def mostrar_todas(request):
    meses_aporte = []
    mes_year = datetime.now().strftime('%Y-%m')
    if request.user.is_staff == True:
        objects = Mes_presupuesto.objects.filter()
    else:
        objects = Mes_presupuesto.objects.filter(profesional = request.user.pk)
        
    context = {
               "btn_enlace": "../cobranza",
               "btn_icono": "arrow_back",
               "titulo": "Cobranza General",
               "meses_aporte":objects
               }
                      
    return render(request, "comun/cobranza/index.html", context)

ProyectoTEA/AppTEA/views/error.py
# -*- coding: utf-8 -*-

from AppTEA.views import *


"""
Vista de error para acceso denegado.
"""
@login_required
def error403(request):
    return render(request, "errores/403.html")

"""
Vista de error para acceso denegado.
"""
@login_required
def error404(request):
    return render(request, "errores/404.html")

"""
Vista de error para acceso denegado.
"""
@login_required
def denegado(request):
    return render(request, "errores/acceso_denegado.html")

ProyectoTEA/AppTEA/views/facturacion.py
# -*- coding: utf-8 -*-

from AppTEA.views import *


"""
Vista del Profesional para mostrar información de facturación.
"""
@permission_required('AppTEA.facturacion', raise_exception=True)
def mostrar(request):
	if request.user.is_staff:
		pacientes = Paciente.objects.all()

	else:
		profesional = Profesional.objects.get(pk=request.user.id)

		pacientes = []

		for pres in profesional.presupuesto_set.all():
			if not pres.paciente in pacientes:
				pacientes.append(pres.paciente)

	context = {
		"pacientes": pacientes,
	}
	return render(request, 'profesional/facturacion/index.html', context)

ProyectoTEA/AppTEA/views/profesional.py
# -*- coding: utf-8 -*-

from AppTEA.views import *
from django.core.management import call_command


"""
Vista del Administrador para gestionar los profesionales existentes.
"""
@permission_required('AppTEA.profesionales', raise_exception=True)
def profesionales(request):
    # Si es Administrador
    if request.user.is_staff:

        if request.method == "POST" and request.is_ajax():
            filtro = request.POST['filtro']
            profesionales = Profesional.objects.filter(Q(first_name__icontains=filtro) | Q(last_name__icontains=filtro),
                                                is_active=True).order_by("first_name")
            ids = []

            for p in profesionales:
                ids.append(p.id)

            return JsonResponse({"ids": ids})

        else:
            context = {"profesionales": Profesional.objects.filter(is_active=True).order_by("first_name"),
                       "btn_enlace": "registrar/",
                       "btn_icono": "add",
                       "placeholder": "Nombre o apellido",
                       "url_filtro": reverse('apptea:profesionales')}
            
            return render(request, "administrador/profesionales/index.html", context)
    else:
        return HttpResponse("Acceso denegado")


"""
Vista del Administrador para registrar profesional.
"""
@permission_required('AppTEA.profesionales', raise_exception=True)
def registrar(request):
    context = { "areas" : Area.objects.order_by("nombre").filter(is_active = True),
               "btn_enlace": "..",
               "btn_icono": "arrow_back"}

    if request.method == 'POST':
        fieldarea = Area.objects.get(pk=int(request.POST['area']))
        fieldrnp = request.POST['rnp']
        if fieldrnp == "":
            context['err'] = "faltan campos"
            return render(request, "administrador/profesionales/registrar.html", context)
        fieldnombres = request.POST['nombres']
        if fieldnombres == "":
            context['err'] = "faltan campos"
            return render(request, "administrador/profesionales/registrar.html", context)
        fieldapellidos = request.POST['apellidos']
        if fielapellidos == "":
            context['err'] = "faltan campos"
            return render(request, "administrador/profesionales/registrar.html", context)
        if request.POST['contra'] == "":
            context['err'] = "faltan campos"
            return render(request, "administrador/profesionales/registrar.html", context)
        fieldcontra = make_password(request.POST['contra'])
        fieldmail = request.POST['mail']
        if fieldmail == "":
            context['err'] = "faltan campos"
            return render(request, "administrador/profesionales/registrar.html", context)
        fielddni = request.POST['dni']
        if fielddni == "":
            context['err'] = "faltan campos"
            return render(request, "administrador/profesionales/registrar.html", context)
        fieldnum_matricula = request.POST['num_matricula']
        if fieldnum_matricula == "":
            context['err'] = "faltan campos"
            return render(request, "administrador/profesionales/registrar.html", context)
        fieldtel_personal = request.POST['tel_personal']
        if fieldtel_personal == "":
            context['err'] = "faltan campos"
            return render(request, "administrador/profesionales/registrar.html", context)
        fieldusername = request.POST['usuario']
        if fieldusername == "":
            context['err'] = "faltan campos"
            return render(request, "administrador/profesionales/registrar.html", context)
        
            
        nuevoProfesional = Profesional(username=fieldusername ,area=fieldarea, rnp=fieldrnp, first_name=fieldnombres, last_name=fieldapellidos, password=fieldcontra, email=fieldmail, dni=fielddni, num_matricula=fieldnum_matricula, tel_personal=fieldtel_personal)
        nuevoProfesional.save()

        call_command('add_groups')

        g = Group.objects.get(name='profesional') 
        g.user_set.add(nuevoProfesional)

        return redirect("..")
    else:
        return render(request, "administrador/profesionales/registrar.html", context)


"""
Vista del Administrador para ver un profesional.
"""
@permission_required('AppTEA.profesionales', raise_exception=True)
def ver(request, id_profesional):
    profesional = Profesional.objects.get(pk = id_profesional)
    
    context = {"btn_enlace": "..",
               "btn_icono": "arrow_back",
               "profesional":profesional}

    return render(request, "administrador/profesionales/ver.html", context)
	

"""
Vista del Administrador para editar profesional.
"""
@permission_required('AppTEA.profesionales', raise_exception=True)
def editar(request, id_profesional):
    profesional = Profesional.objects.get(pk = id_profesional)
    context = {"btn_enlace": "../..",
               "btn_icono": "arrow_back",
               "profesional":profesional,
               "areas" : Area.objects.order_by("nombre").filter(is_active = True)}
         
    if request.POST:
        fieldarea = request.POST['area']
        fieldrnp = request.POST['rnp']
        if fieldrnp == "":
            context['err'] = "faltan campos"
            return render(request, "administrador/profesionales/editar.html", context)
        fieldnombres = request.POST['nombres']
        if fieldnombres == "":
            context['err'] = "faltan campos"
            return render(request, "administrador/profesionales/editar.html", context)
        fieldapellidos = request.POST['apellidos']
        if fielapellidos == "":
            context['err'] = "faltan campos"
            return render(request, "administrador/profesionales/editar.html", context)
        fieldmail = request.POST['mail']
        if fieldmail == "":
            context['err'] = "faltan campos"
            return render(request, "administrador/profesionales/editar.html", context)
        fielddni = request.POST['dni']
        if fielddni == "":
            context['err'] = "faltan campos"
            return render(request, "administrador/profesionales/editar.html", context)
        fieldnum_matricula = request.POST['num_matricula']
        if fieldnum_matricula == "":
            context['err'] = "faltan campos"
            return render(request, "administrador/profesionales/editar.html", context)
        fieldtel_personal = request.POST['tel_personal']
        if fieldtel_personal == "":
            context['err'] = "faltan campos"
            return render(request, "administrador/profesionales/editar.html", context)
        
        profesional.area = Area.objects.get(pk=int(fieldarea))
        profesional.rnp = fieldrnp
        Profesional.first_name = fieldnombres
        profesional.last_name = fieldapellidos
        profesional.email = fieldmail
        profesional.dni = fielddni
        profesional.num_matricula = fieldnum_matricula
        profesional.tel_personal = fieldtel_personal
        
        try:
            fieldpass = request.POST['contra']
            profesional.password = fieldpass
        except MultiValueDictKeyError:
            print request.POST

        profesional.save()
        return redirect("/profesionales")
    else:
              
        return render(request, "administrador/profesionales/editar.html", context)


    
"""
Vista del Administrador para dar de baja profesional.
"""
@permission_required('AppTEA.profesionales', raise_exception=True)
def desactivar(request, id_profesional):
    profesional = Profesional.objects.get(pk = id_profesional)
    if profesional.is_active == True:
        profesional.is_active = False
        profesional.save()
        return redirect("/profesionales")
    else:
        return HttpResponse("el usuario ya esta inactivo")

ProyectoTEA/AppTEA/templates/administrador/profesionales/_form.html
{% extends '_base/base.html' %}

{% load staticfiles %}

{% block body_block %}

<style>
.demo-card-wide > .mdl-card__title {
    color: #999999;
    height: 176px;
    background: url("{% static 'images/header.jpg' %}") center / cover;
}
.demo-card-wide > .mdl-card__menu {
    color: #fff;
}
.mdl-card__title-text {
    font-size: 2.7em;
}
.mdl-card__supporting-text{
    font-size: 1em;
}
</style>
		
		<div class="mdl-grid">
		<div class="mdl-cell mdl-cell--2-col"></div>
		<div class="demo-card-wide mdl-card mdl-shadow--3dp    mdl-cell mdl-cell--8-col mdl-cell--8-col-phone">
		<div class="mdl-card__title">
			{% if err %}<h2 class="mdl-card__title-text" style="color: red;">{{err}}{% else %}<h2 class="mdl-card__title-text">{{ titulo }}{% endif %}</h2>
		</div>
		<div class="mdl-card__supporting-text">



		<form action="{{ accion_form }}" method="POST">
		{% csrf_token %}
			<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
				<input class="mdl-textfield__input" type="text" maxlength="30" name="usuario" value="{{ prof.first_name }}" required autofocus>
				<label class="mdl-textfield__label" for="sample4">Nombre de usuario</label>
				<span class="mdl-textfield__error"></span>
			</div><br>
			<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
				<input class="mdl-textfield__input" type="password" name="contra" {% if pass_req %}required{% endif %}>
				<label class="mdl-textfield__label" for="sample4">Contraseña</label>
				<span class="mdl-textfield__error"></span>
			</div><br>
			<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
				<input class="mdl-textfield__input" type="text" maxlength="8" name="rnp" value="{{ prof.rnp }}" pattern="[0-9.]*">
				<label class="mdl-textfield__label" for="sample4">Registro nacional de proveedores </label>
				<span class="mdl-textfield__error">Ingrese un rnp válido</span>
			</div><br>
			<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
				<input class="mdl-textfield__input" type="text" maxlength="30" name="nombres" value="{{ prof.first_name }}">
				<label class="mdl-textfield__label" for="sample4">Nombres</label>
				<span class="mdl-textfield__error"></span>
			</div><br>
			<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
				<input class="mdl-textfield__input" type="text" maxlength="30" name="apellidos" value="{{ prof.last_name }}">
				<label class="mdl-textfield__label" for="sample4">Apellidos</label>
				<span class="mdl-textfield__error"></span>
			</div><br>			
			<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
				<input maxlength="40" name="mail" class="mdl-textfield__input" type="email" value="{{ prof.email }}" required />
				<label class="mdl-textfield__label">E-Mail</label>
				<span class="mdl-textfield__error">Ingrese una dirección de e-mail válida</span>
			</div><br>
			<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
				<input class="mdl-textfield__input" type="text" maxlength="11" name="dni" value="{{ prof.dni }}" pattern="[0-9]{1,3}[.]{0,1}[0-9]{3}[.]{0,1}[0-9]{3}$">
				<label class="mdl-textfield__label" for="sample4">DNI </label>
				<span class="mdl-textfield__error">Ingrese un DNI válido</span>
			</div><br>
			<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
				<input class="mdl-textfield__input" type="text" maxlength="20" name="num_matricula" value="{{ prof.num_matricula }}" pattern="[0-9.]*">
				<label class="mdl-textfield__label" for="sample4">Numero de matricula </label>
				<span class="mdl-textfield__error"></span>
			</div><br>
			<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
				<input class="mdl-textfield__input" type="text" maxlength="40" name="tel_personal" value="{{ prof.tel_personal }}" pattern="[0-9 -]*">
				<label class="mdl-textfield__label" for="sample4">Telefono personal </label>
				<span class="mdl-textfield__error"></span>
			</div><br>
			<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
				<select class="mdl-textfield__input" name="area">
				{% for area in areas %}
					<option value="{{ area.pk }}" {% if area.pk == area_seleccionada.pk %}selected{% endif %}>{{ area.nombre }}</option>
				{% endfor %}
				</select>
				<label class="mdl-textfield__label" for="sample4">Area </label>
				<span class="mdl-textfield__error"></span>
			</div><br>
			<div class="mdl-card__actions mdl-card--border">
				<input type="submit" value="{{ boton }}" class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" style="color: #78909C;">
			</div>
		</form>
		</div>
		</div>
	
</form>
</center>
{% endblock %}

ProyectoTEA/AppTEA/templates/administrador/profesionales/editar.html
{% url 'apptea:editarProfesional' as accion_url %}

{% include 'administrador/profesionales/_form.html' with titulo='Editar profesional' accion_form=accion_url boton='Guardar' prof=profesional area_seleccionada=profesional.area %}

ProyectoTEA/AppTEA/templates/administrador/profesionales/index.html
{% extends '_base/base.html' %}

{% load staticfiles %}

{% block body_block %}

<link rel="stylesheet" type="text/css" href="{% static 'css/perfil.css' %}" />

{% if user.is_authenticated %}

	<div class="mdl-grid">
		
	{% for profesional in profesionales %}

        {% url 'apptea:verProfesional' profesional.id as accion_ver %}
        {% url 'apptea:editarProfesional' profesional.id as accion_edi %}
        {% url 'apptea:desactivarProfesional' profesional.id as accion_del %}

    	{% include '_base/_card.html' with persona=profesional accion_ver=accion_ver accion_edi=accion_edi accion_del=accion_del nombres=profesional.first_name apellidos=profesional.last_name %}
		
	{% endfor %}
	</div>
	
{% endif %}

{% endblock %}

ProyectoTEA/AppTEA/templates/administrador/profesionales/registrar.html
{% url 'apptea:registrarProf' as accion_url %}

{% include 'administrador/profesionales/_form.html' with titulo='Registrar un nuevo profesional' accion_form=accion_url boton='Registrar profesional' pass_req=True %}

ProyectoTEA/AppTEA/templates/administrador/profesionales/ver.html
{% extends '_base/base.html' %}

{% load staticfiles %}


{% block body_block %}
{% if user.is_authenticated %}	
		<style>
		
		.demo-card-wide > .mdl-card__title {
		color: #999999;
		height: 176px;
		background: url("{% static 'images/transparent.jpg' %}") center / cover;
		}
		.demo-card-wide > .mdl-card__menu {
		color: #fff;
		}
		.mdl-card__title-text {
		font-size: 2.7em;
		}
		.mdl-card__supporting-text{
		font-size: 1em;
		}
		</style>
		
		<div class="mdl-grid">
		<div class="mdl-cell mdl-cell--3-col"></div>
		<div class="demo-card-wide mdl-card mdl-shadow--2dp    mdl-cell mdl-cell--6-col mdl-cell--8-col-phone">
		<div class="mdl-card__title">
			<h2 class="mdl-card__title-text">{{ profesional.first_name }} {{ profesional.last_name }}</h2>
		</div>
		<div class="mdl-card__supporting-text">
				<b>DNI : </b>{{ profesional.dni }}<br>
				<b>Matricula :</b> {{ profesional.matricula }}<br>
				<b>TEL :</b>{{ profesional.tel_personal }}<br>
				<b>CUIT :</b> {{ profesional.cuit }}<br>
				<b>Registro Nacional de Proveedores :</b> {{ paciente.numero_afiliado }}<br>
		</div>
		</div>
		</div>
{% else %}
<h1>acceso denegado</h1>
{% endif %}
{% endblock %}